{
  HOMEPAGE_GET_STARTED_CLICKED: "HOMEPAGE_GET_STARTED_CLICKED",
  USER_DELETED_ACCOUNT: "USER_DELETED_ACCOUNT",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  USER_OPENED_PROJECT_IN_BROWSER: "USER_OPENED_PROJECT_IN_BROWSER",
  USER_VISIT_APPETIZE: "USER_VISIT_APPETIZE",
  USER_CREATED_ACCOUNT: "USER_CREATED_ACCOUNT",
  USER_ENTERED_APPETIZE_CODE_IN_POPOVER: "USER_ENTERED_APPETIZE_CODE_IN_POPOVER",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
  USER_ADDED_SOCIAL_USERNAME: "USER_ADDED_SOCIAL_USERNAME",
  USER_REMOVED_SOCIAL_USERNAME: "USER_REMOVED_SOCIAL_USERNAME",
  USER_UPDATED_EMAIL: "USER_UPDATED_EMAIL",
  USER_UPDATED_PROFILE: "USER_UPDATED_PROFILE",
  USER_UPDATED_SETTINGS: "USER_UPDATED_SETTINGS",
  USER_UPDATED_LIKE: "USER_UPDATED_LIKE",
  USER_UPDATED_PRIVACY: "USER_UPDATED_PRIVACY",
  USER_REMOVED_PROJECT: "USER_REMOVED_PROJECT",
  USER_OPENED_PROJECT: "USER_OPENED_PROJECT",
  USER_SEARCHED: "USER_SEARCHED",
  USER_OPENED_SHARE: "USER_OPENED_SHARE",
  USER_OPENED_AUTHED_NAVIGATION: "USER_OPENED_AUTHED_NAVIGATION",
  USER_STAR_GITHUB: "USER_STAR_GITHUB",
  USER_PAGE_VIEWED: "USER_PAGE_VIEWED",
  USER_CLICKED_CTA: "USER_CLICKED_CTA",
  USER_DELETED_LOGIN_SESSIONS: "USER_DELETED_LOGIN_SESSIONS",
  USER_PURCHASED_PRODUCT: "USER_PURCHASED_PRODUCT",
  USER_VISITED_WITHOUT_PLAN: "USER_VISITED_WITHOUT_PLAN",
  USER_CANCELLED_PLAN: "USER_CANCELLED_PLAN",
  USER_UPDATED_PAYMENT_INFO: "USER_UPDATED_PAYMENT_INFO"
},
{
  DASHBOARD_OVERVIEW_BUILD_CLICKED: "DASHBOARD_OVERVIEW_BUILD_CLICKED",
  DASHBOARD_OVERVIEW_MORE_BUILDS_CLICKED: "DASHBOARD_OVERVIEW_MORE_BUILDS_CLICKED",
  DASHBOARD_BUILDS_BUILD_CLICKED: "DASHBOARD_BUILDS_BUILD_CLICKED",
  DASHBOARD_PROJECTACTIVITY_BUILD_CLICKED: "DASHBOARD_PROJECTACTIVITY_BUILD_CLICKED"
},
{
  BUILDS_INSTALL_CLICKED: "BUILDS_INSTALL_CLICKED",
  BUILDS_DOWNLOAD_CLICKED: "BUILDS_DOWNLOAD_CLICKED",
  BUILDS_DELETE_CLICKED: "BUILDS_DELETE_CLICKED",
  BUILDS_CANCEL_CLICKED: "BUILDS_CANCEL_CLICKED"
},
{
  ORG_CONVERSION_STARTED: "ORG_CONVERSION_STARTED",
  ORG_CONVERSION_COMPLETED: "ORG_CONVERSION_COMPLETED"
},
{
  ACCESS_TOKEN_CREATED: "ACCESS_TOKEN_CREATED",
  ACCESS_TOKEN_DELETED: "ACCESS_TOKEN_DELETED",
  ACCESS_TOKEN_MODIFIED: "ACCESS_TOKEN_MODIFIED"
},
{
  REFERRAL_RECEIVED: "REFERRAL_RECEIVED"
},
{
  USER_2FA_INITIALIZED: "USER_2FA_INITIALIZED",
  USER_2FA_SAVED_RECOVERY_CODES: "USER_2FA_SAVED_RECOVERY_CODES",
  USER_2FA_SET_UP: "USER_2FA_SET_UP",
  USER_2FA_DISABLED: "USER_2FA_DISABLED",
  USER_2FA_REACHED_SCREEN: "USER_2FA_REACHED_SCREEN"
},
{
  USER_SUBMITTED_SIGNUP_FORM: "USER_SUBMITTED_SIGNUP_FORM"
}